export const states = [
  { id: 1, title: "Alabama", value: "AL" },
  { id: 2, title: "Alaska", value: "AK" },
  { id: 3, title: "Arizona", value: "AZ" },
  { id: 4, title: "Arkansas", value: "AR" },
  { id: 5, title: "California", value: "CA" },
  { id: 6, title: "Colorado", value: "CO" },
  { id: 7, title: "Connecticut", value: "CT" },
  { id: 8, title: "Delaware", value: "DE" },
  { id: 9, title: "Florida", value: "FL" },
  { id: 10, title: "Georgia", value: "GA" },
  { id: 11, title: "Hawaii", value: "HI" },
  { id: 12, title: "Idaho", value: "ID" },
  { id: 13, title: "Illinois", value: "IL" },
  { id: 14, title: "Indiana", value: "IN" },
  { id: 15, title: "Iowa", value: "IA" },
  { id: 16, title: "Kansas", value: "KS" },
  { id: 17, title: "Kentucky", value: "KY" },
  { id: 18, title: "Louisiana", value: "LA" },
  { id: 19, title: "Maine", value: "ME" },
  { id: 20, title: "Maryland", value: "MD" },
  { id: 21, title: "Massachusetts", value: "MA" },
  { id: 22, title: "Michigan", value: "MI" },
  { id: 23, title: "Minnesota", value: "MN" },
  { id: 24, title: "Mississippi", value: "MS" },
  { id: 25, title: "Missouri", value: "MO" },
  { id: 26, title: "Montana", value: "MT" },
  { id: 27, title: "Nebraska", value: "NE" },
  { id: 28, title: "Nevada", value: "NV" },
  { id: 29, title: "New Hampshire", value: "NH" },
  { id: 30, title: "New Jersey", value: "NJ" },
  { id: 31, title: "New Mexico", value: "NM" },
  { id: 32, title: "New York", value: "NY" },
  { id: 33, title: "North Carolina", value: "NC" },
  { id: 34, title: "North Dakota", value: "ND" },
  { id: 35, title: "Ohio", value: "OH" },
  { id: 36, title: "Oklahoma", value: "OK" },
  { id: 37, title: "Oregon", value: "OR" },
  { id: 38, title: "Pennsylvania", value: "PA" },
  { id: 39, title: "Puerto Rico", value: "PR" },
  { id: 40, title: "Rhode Island", value: "RI" },
  { id: 41, title: "South Carolina", value: "SC" },
  { id: 42, title: "South Dakota", value: "SD" },
  { id: 43, title: "Tennessee", value: "TN" },
  { id: 44, title: "Texas", value: "TX" },
  { id: 45, title: "Utah", value: "UT" },
  { id: 46, title: "Vermont", value: "VT" },
  { id: 47, title: "Virginia", value: "VA" },
  { id: 48, title: "Washington", value: "WA" },
  { id: 49, title: "Washington DC", value: "DC" },
  { id: 50, title: "West Virginia", value: "WV" },
  { id: 51, title: "Wisconsin", value: "WI" },
  { id: 52, title: "Wyoming", value: "WY" },
  { id: 53, title: "Armed Forces Pacific", value: "AP" },
];
